name: ActualizarRepo

on:
  schedule:
    - cron: '0 0 * * *'   # Todos los días a las 00:00 UTC ≈ 21:00 CLT
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar get_all_repositorios.py
        run: python get_all_repositorios.py

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 🔄 Actualización diaria de repositorios
          commit_user_name: Mts [GitHub Actions]
          commit_user_email: actions@github.com
